---
# this playbook will install and configure the chrony time sync daemon and client

- name: install chrony
  apt:
          name: chrony
          state: present

- name: configure chrony config
  template: 
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: 0644
  notify: restart chrony

- name: start chrony
  service:
    name: chrony
    state: started
    enabled: yes

- name: configure temp limit
  template:
    src: usercfg.txt.j2
    dest: /boot/firmware/usercfg.txt

- name: Remove snapd from Ubuntu
  apt:
    name: snapd
    state: absent
    purge: yes
  when: ansible_distribution == "Ubuntu"

- name: Remove snapd-related directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /snap
    - /var/snap
    - /var/lib/snapd
    - /home/turtle/snap
  when: ansible_distribution == "Ubuntu"

- name: disable unattended upgrades
  service:
    name: unattended-upgrades
    enabled: no
    state: stopped

- name: reboot
  reboot:
    msg: "Rebooting by ansible"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami